sudo: false

language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "pypy"
install:
    - pip install -r dev-requirements.txt
    - pip install .
    - pip install sphinx
script:
    - make lint
    - py.test
    - make doc
